CREATE TABLE IF NOT EXISTS category_skills (
   id          SERIAL,
   name        VARCHAR(250) NOT NULL,
   created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (id)
)